config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	
	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	rescue_from ActiveRecord::RecordNotFound, with: :no_resource_found

	protected
	def no_resource_found
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_article, only: [:show, :edit, :update, :destroy]
	
	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def show
	end

	def edit
		unless @article.user == current_user
			flash[:alert] = 'You can only edit your own article.'
			redirect_to root_path
		end
	end

	def update
		if @article.update(article_params)
			flash[:success] = 'Article has been updated'
			redirect_to @article
		else
			flash[:error] = 'Article has not been updated'
			render :edit
		end
	end

	def create
		@article = Article.create(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = 'Article has been created'
			redirect_to articles_path
		else
			flash.now[:error] = 'Article has not been created'
			render :new
		end
	end

	def destroy
		if @article.destroy
			flash[:success] = 'Article has been deleted'
			redirect_to articles_path
		end
	end

	protected
	
	def no_resource_found
		flash[:error] = 'No article found'
		redirect_to root_path
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :body)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(flash_type)
    case flash_type.to_sym
      when :notice, :success  then 'alert-success'
      when :info    then 'alert-info'
      when :error   then 'alert-danger'
      when :warning then 'alert-warning'
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="row">
	<div class="col-md-12">
		<%=form_for @article, html: {class: 'form-horizontal', role: 'form'} do |f| %>
			
				<%if @article.errors.any? %>
					<div class="panel panel-danger col-md-offset-1">
						<div class="panel-heading">
							<h2 class='panel-title'>
								<%= pluralize(@article.errors.count, 'error') %>
							</h2>
							<div class="panel-body">
								<ul>
									<% @article.errors.full_messages.each do |msg| %>
										<li><%=msg%></li>
									<%end%>
								</ul>
							</div>
						</div>
					</div>
				<%end%>
			<div class="form-group">
				<div class="control-label col-md-1">
					<%=f.label :title %>
				</div>
				<div class="col-md-11">
					<%=f.text_field :title, class: 'form-control' %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-md-1">
					<%=f.label :body %>
				</div>
				<div class="col-md-11">
					<%=f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of Article'%>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-1 col-md-11">
					<%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
				</div>
			</div>
		<%end%>
	</div>
</div>

app/views/articles/edit.html.erb
<h3 class="text-center"> Editing New Article</h3>

<%= render 'form' %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
	<%=link_to 'New Article', new_article_path, class: 'btn btn-primary' %>
<%end%>

<p></p>

<div class="row">
	<div class="col-md-12">
		<%if @articles.present? %>
			<table class='table table-bordered'>
				<thead>
					<tr>
						<th width='30%'>Title</th>
						<th>Body</th>
					</tr>
				</thead>

				<% @articles.each do |article| %>
					<tr>
						<td>
							<%= link_to article.title, article_path(article) %>
							<p>Created by: <%= article.user.email %></p>
						</td>
						<td><%= truncate(article.body, length: 250) %></td>
					</tr>
				<%end%>
			</table>
		<%else%>
			<h1 id="no-articles">No articles created </h1>
		<%end%>
	</div>
</div>

app/views/articles/new.html.erb
<h3 class="text-center"> Adding New Article</h3>

<%= render 'form' %>

app/views/articles/show.html.erb
<article class="article-detail">
	<h1 class="article-detail-title"><%=@article.title%></h1>
	<div class="glyphicon glyphicon-calendar" id="article-date">
			<%=@article.created_at.strftime('%b %d %Y')%>
	</div>
	<div class="article-show-body">
		<%=@article.body%>
	</div>
	<% if user_signed_in? && current_user == @article.user%>
		<%= link_to 'Edit Article', edit_article_path(@article), class: 'btn btn-lg btn-primary btn-space' %>
		<%= link_to 'Delete Article', article_path(@article), method: :delete, class: 'btn btn-lg btn-danger btn-space' %>
	<%end%>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Blog app</a>
          </div>
          <div id="navbar1" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Authors</a></li>
              <% if !user_signed_in? %>
                <li class=""><%= link_to 'Sign up', new_user_registration_path %></li>
                <li class=""><%= link_to 'Sign in', new_user_session_path %></li>
              <%end%>
              <% if user_signed_in? %>
                <li class=""><%= link_to 'Sign out', destroy_user_session_path, method: :delete%></li>
              <%end%>
            </ul> 
          </div>
          <!--/.nav-collapse -->
        </div>
        <!--/.container-fluid -->
      </nav>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |key, message| %>
            <div class="alert <%=flash_class(key)%>">
              <%=message%>
            </div>
          <%end%>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>